"""Exact-rational coverage reduction and independently serialized source hashes."""
from pathlib import Path
from fractions import Fraction
import argparse
import hashlib
import random
import struct
from alpha_numeric_oracle import decode, encode, double


def reduced(values, width, height, scale):
    output = []
    for y in range(0, height, scale):
        for x in range(0, width, scale):
            total, count = Fraction(0), 0
            for v in range(y, min(y + scale, height)):
                for u in range(x, min(x + scale, width)):
                    total = double(total + decode(values[v * width + u]))
                    count += 1
            output.append(encode(double(total / count)))
    return output


def make_cases():
    cases = []
    for index, (width, height) in enumerate([(1,1),(1,9),(9,1),(7,5),(9,7),(2,2),(3,3),(8,8)]):
        rng = random.Random(0xC0A32026 + index)
        special = [0,0x80000000,1,2,0x007fffff,0x00800000,0x3dcccccd,
                   0x3e800000,0x3f000000,0x3f7fffff,0x3f800000]
        values = [special[i % len(special)] if i % 2 == 0 else rng.randrange(0x3f800001)
                  for i in range(width * height)]
        origin = (0,0) if index % 2 == 0 else (11,17)
        for padding in (0,3):
            stride = width + padding
            inputs = []
            for y in range(height):
                inputs += values[y*width:(y+1)*width]
                inputs += [0x7fc12345,0x7f800000,0xff800000][:padding]
            cases.append((origin,width,height,stride,inputs))
    cases += [((0xfffffffe,0xfffffffe),1,1,1,[0x80000000]),
              ((0xfffffffd,0xfffffffc),2,3,2,[0x3f800000]*6),
              ((31,47),7,5,7,[0x3dcccccd]*35),
              ((0,0),3,3,3,[1]*9)]
    return cases


def generate():
    lines = ['// Generated by coverage_source_oracle.py; Fraction stages and hashlib identity.',
             '#pragma once','#include <array>','#include <cstdint>','#include <span>',
             'namespace coverage_source_reference {',
             'struct Case { std::uint32_t x,y,width,height,stride; '
             'std::span<const std::uint32_t> input,native,mip1,mip2; '
             'std::array<std::uint8_t,32> digest; };']
    cases = make_cases()
    rows = []
    for index, (origin,width,height,stride,inputs) in enumerate(cases):
        native = [0 if (inputs[y*stride+x] & 0x7fffffff) == 0 else inputs[y*stride+x]
                  for y in range(height) for x in range(width)]
        outputs = [inputs,native,reduced(native,width,height,2),reduced(native,width,height,4)]
        for kind, values in enumerate(outputs):
            lines.append('inline constexpr std::uint32_t v%d_%d[] = {%s};' %
                         (index,kind,','.join('0x%08xu' % value for value in values)))
        serialized = b'librawops.source.coverage.f32.v1\x00' + \
            struct.pack('<4I',origin[0],origin[1],width,height) + \
            b''.join(struct.pack('<I',value) for value in native)
        digest = hashlib.sha256(serialized).digest()
        rows.append('{%du,%du,%du,%du,%du,v%d_0,v%d_1,v%d_2,v%d_3,{%s}},' %
            (origin[0],origin[1],width,height,stride,index,index,index,index,
             ','.join('0x%02x' % value for value in digest)))
    lines += ['inline constexpr Case cases[] = {'] + rows + ['};','}','']
    return '\n'.join(lines),len(cases)


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    # Hand-calculated odd-edge actual-count and direct mip-2 admission examples.
    assert reduced([0,0x3f800000,0x3f800000],3,1,2)==[0x3f000000,0x3f800000]
    assert reduced([0,0,0x3f800000],3,1,4)==[0x3eaaaaab]
    content,count=generate()
    target=Path(__file__).with_name('coverage_source_v1.hpp')
    if args.check:
        assert target.read_text(encoding='utf-8')==content,'fixture differs from independent oracle'
    else:
        with target.open('w',encoding='utf-8',newline='\n') as stream:stream.write(content)
    print('%d coverage sources: canonical SHA256/native/mip1/mip2 verified' % count)


if __name__=='__main__':main()
