"""Independent frozen nearest-even IEEE-stage mask-refinement fixtures.

Candidate stage functions are retained byte-for-byte as an oracle dependency.
No engine, NumPy, native casts, or production kernel are used for expected data.
"""
from fractions import Fraction as Q
from pathlib import Path
import argparse,hashlib,json,random
from alpha_numeric_oracle import decode,encode,double,power
from coverage_source_oracle import reduced
from mask_refinement_candidate_oracle import density,feather,refine,checks,word


def b64(v): return encode(Q(v),53,11)
def d64(v): return decode(v,53,11)


def density_cases():
    rng=random.Random(0xFEA72026)
    bases=[0,0x80000000,1,2,3,0x007fffff,0x00800000,0x3e800000,0x3f000000,0x3f7fffff,0x3f800000]
    controls=[Q(0),power(-1074),power(-53),Q(1,8),Q(1,4),Q(1,2),Q(3,4),Q(7,8),1-power(-53),Q(1)]
    cases=[(a,b64(d),density([a],d)[0]) for a in bases for d in controls]
    for _ in range(128):
        a=rng.randrange(0x3f800001)
        d=d64(rng.randrange(0x3ff0000000000001))
        cases.append((a,b64(d),density([a],d)[0]))
    return cases


def metadata():
    rng=random.Random(0xED6E2026)
    result=[]
    dims=((0,0,1,1),(17,23,7,1),(31,47,1,7),(0,0,5,3),
          (5,9,4,4),(0xfffffff0,0xfffffff1,3,3))
    patterns=[0,0x80000000,1,3,0x007fffff,0x00800000,word(Q(1,4)),word(Q(1,2)),word(1)]
    for fi,(x,y,w,h) in enumerate(dims):
        p=[patterns[(i+fi)%len(patterns)] for i in range(w*h)]
        if fi==4: p=[rng.randrange(0x3f800001) for _ in range(w*h)]
        guides=[word(v) for i in range(w*h) for v in (Q(i%3)-1,Q(i%5,4),Q(i%7,2))]
        if fi==5:
            extremes=[0x7f7fffff,0xff7fffff,1,0x80000001,0x007fffff,0x00800000,0,0x80000000]
            guides=[extremes[(i*3+i//3)%len(extremes)] for i in range(3*w*h)]
        settings=[(0,0,b64(d),0) for d in (0,Q(1,4),Q(1,2),1-power(-53),1)]
        settings += [(1,r,0,0) for r in (0,1,2,3,8,32)]
        settings += [(2,r,b64(e),s) for s in (0,1) for r in (0,1,8)
                     for e in (power(-24),Q(65536))]
        for kind,radius,control,space in settings:
            result.append(dict(x=x,y=y,width=w,height=h,kind=kind,radius=radius,
                               control=control,space=space,input=p,guide=guides))
    return result


def input_region(f,mip,x,y):
    scale=1<<mip
    halo=f['radius']*(2 if f['kind']==2 else 1) if f['kind'] else 0
    left=max(0,x*scale-halo);top=max(0,y*scale-halo)
    right=min(f['width'],(x+1)*scale+halo);bottom=min(f['height'],(y+1)*scale+halo)
    return (f['x']+left,f['y']+top,right-left,bottom-top)


def operations():
    params=({'density':1},{'radius':0},{'radius':3,'epsilon':0.000244140625})
    result=[]
    for kind,typ in enumerate(('rawengine.mask_density','rawengine.mask_feather_binomial','rawengine.mask_refine_working_y')):
        inputs={'mask':'a4000000-0000-0000-0000-000000000001'}
        if kind==2: inputs['image']='a4000000-0000-0000-0000-000000000002'
        operation=dict(id='a4000000-0000-0000-0000-000000000003',type=typ,
                       schema_version=1,processing_version=2,enabled=True,
                       input_domain='coverage',output_domain='coverage',parameters=params[kind],
                       inputs=inputs,masks={},blend_mode='normal',opacity=1.0)
        result.append(json.dumps(operation,sort_keys=True,separators=(',',':')))
    return result


def resource_checks():
    # Pure integer payload/envelope proof, including uint32 boundary origins.
    count=0;peak=dict(feather=0,refine=0)
    for w,h in ((1,1),(7,5),(256,256),(0xffffffff,1),(1,0xffffffff)):
        for r in (0,1,8,32):
            n=(w+2*r)*(h+2*r);horizontal=w*(h+2*r)
            payload=4*n+8*horizontal+4*w*h
            assert payload>=4*w*h
            if w==h==256:peak['feather']=max(peak['feather'],payload)
            count+=1
        for r in (0,1,8):
            n=(w+4*r)*(h+4*r);a=(w+2*r)*(h+2*r)
            payload=16*n+24*a+4*w*h
            assert payload>=4*w*h
            if w==h==256:peak['refine']=max(peak['refine'],payload)
            count+=1
    return count,peak


def generate():
    counts=checks();cases=density_cases();frames=metadata();roi_rows=[]
    lines=['// Generated by mask_refinement_oracle.py; exact Fraction IEEE stages.',
           '#pragma once','#include <array>','#include <cstdint>','#include <span>',
           'namespace mask_refinement_reference {',
           'struct DensityCase { std::uint32_t input; std::uint64_t density; std::uint32_t output; };',
           'struct Frame { std::uint32_t x,y,width,height; int kind,radius,space; std::uint64_t control; std::span<const std::uint32_t> input,guide,native,mip1,mip2; };',
           'struct Cell { int frame,mip; std::uint32_t x,y; std::array<std::uint32_t,4> input_region; std::uint32_t output; };',
           'inline constexpr DensityCase density_cases[] = {']
    lines += ['{0x%08xu,0x%016xull,0x%08xu},'%v for v in cases]+['};']
    frame_rows=[]
    words=lambda vs:'{'+','.join('0x%08xu'%v for v in vs)+'}'
    for index,f in enumerate(frames):
        w,h=f['width'],f['height'];kind=f['kind'];r=f['radius']
        if kind==0:out=density(f['input'],d64(f['control']))
        elif kind==1:out=feather(f['input'],w,h,r)
        else:out=refine(f['input'],f['guide'],w,h,r,d64(f['control']),f['space'])
        assert all(0<=decode(v)<=1 for v in out)
        f.update(native=out,mip1=reduced(out,w,h,2),mip2=reduced(out,w,h,4))
        for suffix in ('input','guide','native','mip1','mip2'):
            lines.append('inline constexpr std::uint32_t frame%d_%s[] = %s;'%(index,suffix,words(f[suffix])))
        frame_rows.append('{%du,%du,%du,%du,%d,%d,%d,0x%016xull,frame%d_input,frame%d_guide,frame%d_native,frame%d_mip1,frame%d_mip2},'%
                          (f['x'],f['y'],w,h,kind,r,f['space'],f['control'],index,index,index,index,index))
        for mip in (0,1,2):
            scale=1<<mip;rw=(w+scale-1)//scale;rh=(h+scale-1)//scale
            outputs=f['native' if not mip else 'mip%d'%mip]
            for y in range(rh):
                for x in range(rw):
                    region=input_region(f,mip,x,y)
                    assert f['x']<=region[0]<f['x']+w and f['y']<=region[1]<f['y']+h
                    assert region[0]+region[2]<=f['x']+w and region[1]+region[3]<=f['y']+h
                    roi_rows.append('{%d,%d,%du,%du,{%du,%du,%du,%du},0x%08xu},'%
                                    (index,mip,x,y,*region,outputs[y*rw+x]))
    lines += ['inline constexpr Frame frames[] = {']+frame_rows+['};',
              'inline constexpr Cell cells[] = {']+roi_rows+['};']
    for i,operation in enumerate(operations()):
        lines += ['inline constexpr char operation%d_json[] = R"json(%s)json";'%(i,operation),
                  'inline constexpr char operation%d_sha256[] = "%s";'%(i,hashlib.sha256(operation.encode()).hexdigest())]
    lines += ['}','']
    resource_count,peak=resource_checks()
    counts.update(density_cases=len(cases),frames=len(frames),cell_rois=len(roi_rows),
                  resource_cases=resource_count,unclipped_256_square_payload=peak,
                  arithmetic='IEEE nearest-even stage oracle; native and other rounding modes remain unverified')
    return '\n'.join(lines),counts


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    content,counts=generate();target=Path(__file__).with_name('mask_refinement_v1.hpp')
    if args.check:assert target.read_text(encoding='utf-8')==content,'fixture differs from independent oracle'
    else:
        with target.open('w',encoding='utf-8',newline='\n') as stream:stream.write(content)
    print(json.dumps(counts,sort_keys=True),flush=True)


if __name__=='__main__':main()
