"""Independent rational oracle for staged coverage algebra and masked RGB mix."""
from pathlib import Path
from fractions import Fraction as Q
import argparse,random
from alpha_numeric_oracle import decode,encode,double,FMAX
from coverage_source_oracle import reduced

def algebra(mode,a,b):
    a,b=decode(a),decode(b)
    if mode==0:value=double(1-a)
    elif mode==1:value=min(Q(1),double(a+b))
    elif mode==2:value=max(Q(0),double(a-b))
    else:value=double(a*b)
    return encode(value)

def mix(base,layer,mask,amount):
    weight=double(decode(mask)*decode(amount,53,11))
    if weight==0:return base
    if weight==1:return layer
    output=[]
    for b,l in zip(base,layer):
        if b==l:output.append(b);continue
        delta=double(decode(l)-decode(b))
        mapped=double(decode(b)+double(weight*delta))
        if abs(mapped)>FMAX:raise OverflowError
        output.append(encode(mapped))
    return output

def generate():
    rng=random.Random(0xAA542026)
    coverage=[0,1,0x007fffff,0x00800000,0x3dcccccd,0x3e800000,0x3f000000,0x3f7fffff,0x3f800000]
    amounts=[0,1,0x0170000000000000,0x3fd0000000000000,0x3fe0000000000000,
             0x3fefffffffffffff,0x3ff0000000000000]
    lines=['// Generated by mask_graph_numeric_oracle.py; Fraction arithmetic.',
           '#pragma once','#include <array>','#include <cstdint>',
           'namespace mask_graph_reference {',
           'struct Algebra { int mode; std::uint32_t a,b,output; };',
           'inline constexpr Algebra algebra[] = {']
    count=0
    for a in coverage:
        for b in coverage:
            for mode in range(4):
                lines.append('{%d,0x%08xu,0x%08xu,0x%08xu},'%(mode,a,b,algebra(mode,a,b)))
                count+=1
    lines+=['};','struct Mix { std::array<std::uint32_t,3> base,layer; '
            'std::uint32_t mask; std::uint64_t amount; std::array<std::uint32_t,3> output; bool overflow; };',
            'inline constexpr Mix mixes[] = {']
    fmt=lambda words:'{'+','.join('0x%08xu'%x for x in words)+'}'
    n=0
    for i in range(180):
        def color():return rng.randrange(0x7f800000)|(rng.randrange(2)<<31)
        base=[color(),color(),color()];layer=[color(),color(),color()]
        if i%5==0:base=[0x7f7fffff,0xff7fffff,0x3f800000];layer=[0xff7fffff,0x7f7fffff,0xbf800000]
        if i%7==0:layer=base[:]
        mask=coverage[i%len(coverage)];amount=amounts[(i//len(coverage))%len(amounts)]
        try:output=mix(base,layer,mask,amount);overflow=False
        except OverflowError:output=[0,0,0];overflow=True
        lines.append('{%s,%s,0x%08xu,0x%016xull,%s,%s},'%
                     (fmt(base),fmt(layer),mask,amount,fmt(output),str(overflow).lower()))
        n+=1
    lines+=['};']
    base=[];layer=[];mask_a=[];mask_b=[]
    for i in range(35):
        pixel=[encode(Q(i%9-4,4)),encode(Q(i//7+1,4)),encode(Q(i%7-2,2))]
        base.extend(pixel);layer.extend(encode(decode(x)*2) for x in pixel)
        a=encode(Q(i%5,4));mask_a.append(a);mask_b.append(encode(1-decode(a)))
    def array(name,words):
        lines.append('inline constexpr std::uint32_t %s[] = {%s};'%(name,','.join('0x%08xu'%x for x in words)))
    array('base_rgb',base);array('layer_rgb',layer);array('mask_a',mask_a);array('mask_b',mask_b)
    for mip,scale in enumerate((1,2,4)):
        def rgb_level(words):
            planes=[reduced(words[c::3],7,5,scale) for c in range(3)]
            return [word for pixel in zip(*planes) for word in pixel]
        b,l=rgb_level(base),rgb_level(layer)
        ma,mb=reduced(mask_a,7,5,scale),reduced(mask_b,7,5,scale)
        coverage=[algebra(3,algebra(0,a,0),other) for a,other in zip(ma,mb)]
        output=[]
        for i,c in enumerate(coverage):output+=mix(b[i*3:i*3+3],l[i*3:i*3+3],c,0x3fe0000000000000)
        array('coverage_mip%d'%mip,coverage);array('mixed_mip%d'%mip,output)
    lines+=['}','']
    return '\n'.join(lines),count,n

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    assert algebra(1,0x3f000000,0x3f000000)==0x3f800000
    assert algebra(2,0x3e800000,0x3f000000)==0
    assert algebra(3,0x3f000000,0x3f000000)==0x3e800000
    text,count,n=generate();target=Path(__file__).with_name('mask_graph_numeric_v1.hpp')
    if args.check:assert target.read_text(encoding='utf-8')==text
    else:
        with target.open('w',encoding='utf-8',newline='\n') as stream:stream.write(text)
    print('%d algebra/%d staged masked RGB cases and3 full chain levels verified'%(count,n))

if __name__=='__main__':main()
