"""Independent exact-rational fixtures for typed native RGBA graphs.

Uses frozen alpha equations and explicit IEEE stages; never loads the engine.
"""
from pathlib import Path
from fractions import Fraction as Q
import argparse
import hashlib
import struct
from alpha_numeric_oracle import decode, encode, double, expected


def canonical(words):
    return [0]*4 if not decode(words[3]) else words[:]


def reduced(values, width, height, channels, mip):
    if not mip:
        return values[:]
    scale = 1 << mip
    output = []
    for y in range(0, height, scale):
        for x in range(0, width, scale):
            count = min(scale, height-y)*min(scale, width-x)
            pixel = []
            for c in range(channels):
                total = Q(0)
                for v in range(y, min(height, y+scale)):
                    for u in range(x, min(width, x+scale)):
                        total = double(total + decode(values[(v*width+u)*channels+c]))
                pixel.append(encode(double(total/count)))
            if channels == 4 and not decode(pixel[3]):
                pixel = [0]*4
            output += pixel
    return output


def fingerprint(bounds, space, words):
    data = b'librawops.source.rgba.premult.f32.v1\0'
    data += struct.pack('<5I', *bounds, space)
    data += b''.join(struct.pack('<I', v) for v in words)
    return list(hashlib.sha256(data).digest())


def generate():
    frames = []
    shapes = [(1,1),(1,5),(5,1),(3,3),(4,2),(7,5),(2,3)]
    alphas = [0, 0x3e800000, 0x3f000000, 0x3f800000, 1, 0x00800000]
    for space in (1,2):
        for kind in range(6):  # source, premultiply, coverage, over, alpha, straight
            for shape_index, (width,height) in enumerate(shapes):
                origin = (0,0) if shape_index == 0 else (11,17)
                if shape_index == 6:
                    origin = (0xffffffff-width,0xffffffff-height)
                bounds = (*origin,width,height)
                source, backdrop, mask = [], [], []
                for i in range(width*height):
                    a = alphas[(i+shape_index)%len(alphas)]
                    color = [encode(Q((i*7+c*5)%17-8,4)) for c in range(3)]
                    p = canonical(color+[a])
                    # Keep the straight adapter's positive tiny-alpha cases finite.
                    if kind == 5 and a in (1,0x00800000):
                        p = [a, a|0x80000000, 0, a]
                    source += color+[a] if kind == 1 else p
                    ba = alphas[(i*3+2)%4]
                    backdrop += canonical([encode(Q(c+1,2)) for c in range(3)]+[ba])
                    mask.append(alphas[(i*5+shape_index)%len(alphas)])
                channels = 1 if kind == 4 else 3 if kind == 5 else 4
                native = []
                for i in range(width*height):
                    s, b = source[i*4:i*4+4], backdrop[i*4:i*4+4]
                    if kind == 0:
                        native += s
                    elif kind == 1:
                        native += expected(0,s+[0]*4)
                    elif kind == 2:
                        native += expected(1,s+[mask[i],0,0,0])
                    elif kind == 3:
                        native += expected(2,s+b)
                    elif kind == 4:
                        native += [s[3]]
                    else:
                        native += expected(3,s+[0]*4)[:3]
                levels = [reduced(native,width,height,channels,m) for m in range(3)]
                digest = fingerprint(bounds,space,native) if channels == 4 else [0]*32
                frames.append((kind,space,bounds,source,backdrop,mask,levels,digest))
    # Independent hand-computable ordering witnesses.
    assert reduced([encode(Q(2)),0,0,encode(Q(1)),0,0,0,0],2,1,4,1) == \
        [encode(Q(1)),0,0,encode(Q(1,2))]
    # Straight before reduction: (2 + 0)/2 = 1; straight after RGBA reduction = 2.
    straight = reduced([encode(Q(2)),0,0,0,0,0],2,1,3,1)
    assert straight[0] == encode(Q(1))
    assert expected(3,[encode(Q(1)),0,0,encode(Q(1,2))]+[0]*4)[0] == encode(Q(2))
    fmt = lambda values: '{'+','.join('0x%08xu'%v for v in values)+'}'
    lines = ['// Generated by rgba_native_oracle.py; Fraction/IEEE stages and hashlib.',
             '#pragma once', '#include <array>', '#include <cstdint>', '#include <vector>',
             'namespace rgba_native_reference {',
             'struct Frame { int kind,space; std::array<std::uint32_t,4> bounds; '
             'std::vector<std::uint32_t> source,backdrop,mask; '
             'std::array<std::vector<std::uint32_t>,3> levels; std::array<std::uint32_t,32> fingerprint; };',
             'inline const Frame frames[] = {']
    for kind,space,bounds,source,backdrop,mask,levels,digest in frames:
        lines.append('{%d,%d,%s,%s,%s,%s,{{%s,%s,%s}},%s},' %
                     (kind,space,fmt(bounds),fmt(source),fmt(backdrop),fmt(mask),
                      *(fmt(v) for v in levels),fmt(digest)))
    lines += ['};', '} // namespace rgba_native_reference', '']
    return '\n'.join(lines), len(frames)


def main():
    args = argparse.ArgumentParser()
    args.add_argument('--check', action='store_true')
    option = args.parse_args()
    content, count = generate()
    path = Path(__file__).with_name('rgba_native_v1.hpp')
    if option.check:
        assert path.read_text(encoding='utf-8') == content
    else:
        with path.open('w',encoding='utf-8',newline='\n') as stream:
            stream.write(content)
    print('{} frames / 3 frozen levels / independent SHA256 verified'.format(count))


if __name__ == '__main__':
    main()
